module.exports = [
    {
        ref: "T0001",
        description: "Basic usage",
        schema: { test: { $type: "string", $required: true } },
        data: { test: "Hello world" },
        compileError: false,
        error: false,
        encode: { test: "Hello world" },
        strictDecode: { test: "Hello world" },
        decode: { test: "Hello world" },
        strictVerify: { test: "Hello world" },
        verify: { test: "Hello world" }
    },
    {
        ref: "T0002",
        description: "Checking $min",
        schema: { test: { $type: "string", $min: 100, $required: true } },
        data: { test: "Hello world" },
        compileError: false,
        error: true,
        encodeError: false,
    },
    {
        ref: "T0003",
        description: "Checking $max",
        schema: { test: { $type: "string", $max: 10, $required: true } },
        data: { test: "Hello world" },
        compileError: false,
        error: true,
        encodeError: false,
    },
    {
        ref: "T0004",
        description: "Checking $strict",
        schema: { test: { $type: "string", $strict: true, $required: true } },
        data: { test: "Hello!world" },
        compileError: false,
        error: true,
        encodeError: false,
    },
    {
        ref: "T0005",
        description: "Checking $unicode",
        schema: { test: { $type: "string", $unicode: false, $required: true } },
        data: { test: "Helloéworld" },
        compileError: false,
        error: true,
        encodeError: false,
    },
]